on:
  push:
      branches:
        - master

jobs:
  create_cv_pdf:
    runs-on: ubuntu-20.04
    steps:
      - name: Create PDF
        run: |
          sudo apt-get update &&
          sudo apt-get install --no-install-recommends -y wkhtmltopdf &&
          wkhtmltopdf -T 0 -B 0 -L 0 -R 0 --page-size A4 --dpi 600 https://julianbusch.ch julianbusch-cv.pdf
      - name: Archive PDF
        uses: actions/upload-artifact@v3
        with:
          name: julianbusch-cv
          path: julianbusch-cv.pdf